/*
 * This file is part of mix-calculator, a Schedule One mix calculator.
 * Copyright (C) 2025  Joe Desmond
 *
 * mix-calculator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * mix-calculator is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with mix-calculator.  If not, see <https://www.gnu.org/licenses/>.
 */
import React from "preact";

export const Attributions: React.FunctionComponent = () => {
    return (
        <main>
            <h1>Attributions</h1>
            <section>
                <section>
                    <p>
                        The algorithm was taken from <a href="https://www.scheduleonegame.com/">Schedule One</a>.
                    </p>
                    <p>
                        <a href="https://github.com/Perfare/Il2CppDumper">Il2CppDumper</a> was used to dump game
                        metadata and symbols, and <a href="https://github.com/NationalSecurityAgency/ghidra">Ghidra</a>{" "}
                        was used to decompile the binary.
                    </p>
                    <p>
                        <a href="https://learn.microsoft.com/en-us/windows-hardware/drivers/debuggercmds/windbg-overview">WinDbg</a>{" "}
                        was used to inspect memory at runtime, and <a href="https://github.com/Dezzmeister/SynTypesTS">SynTypesTS</a>{" "}
                        (my own extension) was used to define types and dump memory as JSON.
                    </p>
                </section>
                <hr />
                <section>
                    <p>
                        The site icon <img src="/blue.svg" width="12"/> was generated by GitHub Copilot.
                    </p>
                </section>
                <hr />
                <section>
                    <p>
                        This site was built with <a href="https://preactjs.com/">Preact</a> and
                        {" "}<a href="https://www.typescriptlang.org/">Typescript</a>.
                        The site is served by <a href="https://github.com/Dezzmeister/gru-http">gru-http</a> (my own web server)
                        behind <a href="https://nginx.org/">nginx</a> for TLS.
                    </p>
                    <p>
                        gru-http is licensed under the GNU Affero Public License 3 or any later version at your choice. See
                        {" "}<a href="https://github.com/Dezzmeister/gru-http/blob/master/COPYING">COPYING</a> for details.
                    </p>
                </section>
                <hr />
                <section>
                    <p>
                        Source code for mix-calculator is available at
                        {" "}<a href="https://github.com/Dezzmeister/mix-calculator">https://github.com/Dezzmeister/mix-calculator</a>.
                    </p>
                    <p>
                        mix-calculator is licensed under the GNU Affero Public License 3 or any later version at your choice. See
                        {" "}<a href="https://github.com/Dezzmeister/mix-calculator/blob/master/COPYING">COPYING</a> for details.
                    </p>
                </section>
            </section>
        </main>
    );
};